fixed bigiq_license lookup plugin issue
F5Networks/f5-ansible pull request #1975
Opened 2021-02-24 18:08 UTC by RavinderReddyF5

2021-02-25 11:10 UTC, wojtek0806 requested changes

2021-02-25 11:10 UTC, wojtek0806 commented on ansible_collections/f5networks/f5_modules/plugins/module_utils/bigiq.py
>          if provider != 'local':
code needs to be spaced out for readability

2021-02-25 11:10 UTC, wojtek0806 commented on ansible_collections/f5networks/f5_modules/plugins/module_utils/bigiq.py
>          return session, None
space out code for readability

2021-02-25 11:10 UTC, wojtek0806 commented on ansible_collections/f5networks/f5_modules/plugins/lookup/bigiq_license.py
> +        return regKeypool
This is supposed to be a single key from a list not the entire list

2021-02-25 11:10 UTC, wojtek0806 commented
rebase squash commits, make sure tests pass and i will rereview :)

2021-03-22 09:37 UTC, RavinderReddyF5 reviewed
review comments addressed and fixed build issues

2021-03-22 10:01 UTC, merged