Added auto_last_hop parameter for bigip_virtual_server module
F5Networks/f5-ansible pull request #2128
Opened 2021-11-11 04:08 UTC by urohit011

Fixes #2104 

Tests:

(venv-3.9) ➜  repro$ ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_virtual_server.yaml -t "issue-02104" --step

PLAY [Metadata of bigip_virtual_server] ******************************************************************************************************************************************

PLAY [Test the bigip_virtual_server module - Environment] ************************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y

Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [bigip1]
Perform task: TASK: bigip_virtual_server : Issue 02104 - Add virtual server (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Add virtual server (N)o/(y)es/(c)ontinue: *******************************************************************************

TASK [bigip_virtual_server : Issue 02104 - Add virtual server] *******************************************************************************************************************
changed: [bigip1]
Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to enabled (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to enabled (N)o/(y)es/(c)ontinue: ******************************************************************

TASK [bigip_virtual_server : Issue 02104 - Change auto last hop to enabled] ******************************************************************************************************
changed: [bigip1]
Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to enabled (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to enabled (N)o/(y)es/(c)ontinue: ***********************************************************

TASK [bigip_virtual_server : Issue 02104 - Assert Change auto last hop to enabled] ***********************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}
Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to enabled - Idempotent Check (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to enabled - Idempotent Check (N)o/(y)es/(c)ontinue: ***********************************************

TASK [bigip_virtual_server : Issue 02104 - Change auto last hop to enabled - Idempotent Check] ***********************************************************************************
ok: [bigip1]
Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to enabled - Idempotent Check (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to enabled - Idempotent Check (N)o/(y)es/(c)ontinue: ****************************************

TASK [bigip_virtual_server : Issue 02104 - Assert Change auto last hop to enabled - Idempotent Check] ****************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}
Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to disabled (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to disabled (N)o/(y)es/(c)ontinue: *****************************************************************

TASK [bigip_virtual_server : Issue 02104 - Change auto last hop to disabled] *****************************************************************************************************
changed: [bigip1]
Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to disabled (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to disabled (N)o/(y)es/(c)ontinue: **********************************************************

TASK [bigip_virtual_server : Issue 02104 - Assert Change auto last hop to disabled] **********************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}
Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to disabled - Idempotent Check (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Change auto last hop to disabled - Idempotent Check (N)o/(y)es/(c)ontinue: **********************************************

TASK [bigip_virtual_server : Issue 02104 - Change auto last hop to disabled - Idempotent Check] **********************************************************************************
ok: [bigip1]
Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to disabled - Idempotent Check (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Assert Change auto last hop to disabled - Idempotent Check (N)o/(y)es/(c)ontinue: ***************************************

TASK [bigip_virtual_server : Issue 02104 - Assert Change auto last hop to disabled - Idempotent Check] ***************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}
Perform task: TASK: bigip_virtual_server : Issue 02104 - Remove virtual server (N)o/(y)es/(c)ontinue: y

Perform task: TASK: bigip_virtual_server : Issue 02104 - Remove virtual server (N)o/(y)es/(c)ontinue: ****************************************************************************

TASK [bigip_virtual_server : Issue 02104 - Remove virtual server] ****************************************************************************************************************
changed: [bigip1]

PLAY [Test the bigip_virtual_server module - Provider] ***************************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y

Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [bigip1]

PLAY RECAP ***********************************************************************************************************************************************************************
bigip1                     : ok=12   changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

(venv-3.9) ➜  repro
(venv-3.9) ➜  repro ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_virtual_server.yaml -t "issue-02104" --step
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [Metadata of bigip_virtual_server] ******************************************************************************************************************************************

PLAY [Test the bigip_virtual_server module - Environment] ************************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y

Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************************************************************

TASK [Gathering Facts] ************************ [...]

2021-11-11 07:18 UTC, RavinderReddyF5 commented
looks good to me

2021-11-18 22:01 UTC, wojtek0806 requested changes
make the requested changes and retest after that it should be ok :)

2021-11-18 22:01 UTC, wojtek0806 commented on ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py
> +                default='default',
you might wanna remove default, if a user modifies a  VS which has this value set to something else, and the user does not specfiy it in their play, the module will override it on the device

2021-11-19 11:14 UTC, urohit011 commented
Hi @wojtek0806, I have made the changes you suggested.

2021-11-22 07:23 UTC, wojtek0806 approved these changes

2021-11-22 07:24 UTC, merged