fix for source capability for bigip_device_auth_ldap module
F5Networks/f5-ansible pull request #2129
Opened 2021-11-11 05:39 UTC by RavinderReddyF5

2021-11-18 22:03 UTC, wojtek0806 requested changes
change the file as requested, do we need to have tests here?

2021-11-18 22:03 UTC, wojtek0806 commented on ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
> +    default: ldap
`version_added: "1.13.0"`

2021-11-22 18:06 UTC, RavinderReddyF5 commented on ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
> +    default: ldap
updated

2021-11-22 18:07 UTC, RavinderReddyF5 commented on ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
> +    default: ldap
tests also added

2021-11-26 07:43 UTC, wojtek0806 approved these changes

2021-11-26 07:43 UTC, merged